### ISSUE TITLE
Add Cake Addin to Website

### ISSUE THREAD

**Issue by gep13** [alexreg/Cake.RoslynAnalyzers#1]
Great work on getting this addin created!

This is just a suggestion, but think it would be a really good idea, to help with visibility of this addin.

i.e. get your addin listed here:

http://cakebuild.net/addins

Have a look at this PR:

cake-build/website#290

This assumes that you have added XML Documentation to your addin, as described here:

http://cakebuild.net/docs/contributing/documentation

Let me know if you have any questions. Thanks!

**Comment by alexreg** [comment]
Hi @gep13. Thanks for the message. I started writing this add-in, but then found out how tightly the Roslyn analyzers are integrated with MSBuild, and started having doubts over the utility of such a cake add-in. In fact, I just edit my MSBuild files now, and that seems to do the trick. If you see otherwise though, perhaps I can maintain this...

**Comment by gep13** [comment]
@alexreg Happy to take your lead on this.  The reason that I raised the issues is that I saw that you pushed a package to NuGet.org.  Perhaps you should unlist the package if is isn't something that you are going to continue with?

**Comment by alexreg** [comment]
Sure, will do.

**Comment by gep13** [comment]
@alexreg let me know what you plan on doing here, and I can update the list that I am maintaining of Cake addins, thanks.

**Comment by alexreg** [comment]
@gep13 It's delisted on Nuget now, so no need to have it on the official Nuget site. Thanks.

(Please close this issue if all is good with you now.)

**Comment by gep13** [comment]
@alexreg thanks for taking care of this!

**Comment by alexreg** [comment]
No problem.

**Comment by gep13** [comment]
@alexreg just wanted to cycle back about this package...

Seems like it is still listed on nuget.org, is that intentional?  Thanks!
